language: python
python:
- '3.5'
- '3.6'

install:
- sudo apt-get update
- pip install -r requirements.txt
- pip install .

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

script:
- python setup.py test

deploy:
  # pypy test deployment
  - provider: pypi
    distributions: sdist
    server: https://test.pypi.org/legacy/
    user: cklb
    password:
      secure: I2pYYSnlBGy2gI2TfPZrgs51Ovn0NvACz9LrsmqEfJ/ZFNKRnvtsR+2YwyIFLKYPfR7Cw61gFGxfXg6Ed9+CRvoRHlsDT1uVL/gXx+qB5dzHHkiYXvzvhxjMPdzhj33Mr1LL0UNMp6Vwl5AULQjhgJoPDGtyitxUdhlL6VPajwuDgkrhV0NmqfCPq+H7YYqkAZb9Kuwf7JFY0zTWmmknt7i0D77ulQK3/uqNNSJQmPV8RURFPVj+6J8AttrKg6VPKDDF9uMAqIgNS2IE+KbhQ93wn7hL6kqm5mrnqorMi+UhsQuX8kXv2GjFQVYGmowo2apZXj3dJR3/xOHzBEB4U3kA4jIxqLwl1lgJAhzjwHZ+7jNfWXHaq0z8wNWGBegBPkVtultIH12RpO9e+fK/h+TYAoDqQaPz9ji75fduVkohHH94XjnWR7B9QUsADmR6tmWIT87/9sb3AqL3AeHi/LYgqoSScZ/b9K5ViuWgnIrpMxvK75yfyKC1FgNN9/s2HRa6CGryqve8RUYTrA6+10xXKs8c90NCacnOA6zPq51xezRLRaDBid8XYwVGRmj4oz+5SWLOkDOpSnw2ErpayyRcJmwGohQ6Drc/jEaMZxWp+yaa/At8okQQruEiQdHTXiIqkdvHmJmnKDtzBvY34Y4edfki/UIWHYKcZ08FA6o=
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "3.6"

  # pypy deployment
  - provider: pypi
    distributions: sdist
    user: cklb
    password:
      secure: WKFKDgsXpoNPPedpgG6W7avL7CHbsFYtTbd41QlnJiBd2qBsI0x2qYsGVrQgC8adCwh8prXCLp+Xs+xR259tyGo6uzrJg/6WyNx5D9IWORizUI7Wa3odYwoK0jN/vK4Rq9TttKbCYI7hjQFs0Dbj+wIZMuPdutqVBSTfPEbOZYKBN2wrqO0gtH5Wc4wjEvWSrGacxmJ1gQaZqwu0LsgbQPjH7wFFV6qX//gOQUEaRNWU6UjoJnLVFV3bhc2GmdGRx7y2qUkP7SQmJoGCB2rtWOT+DeMjbZqq1IplUoWZPJs8cSei8nm+L1wA4DhFUVbm1IhhSHREpMA+KwLbygp79ml2QCOvrHmU+T5SmyHkvI8FJAMX28KuinUU2RC4VIJuvKhTS+IS7yBKOoV1lismMgGbtWafhEHUz6YKOoIDjSPaNOA1/9E2xsIxBXeFmoEDx6tO4wCGT3/da79e8b5Iv6gDR0LdqMD4Dmfzdy7CAbHFw21QwwncSc6t6scYUPUHMfFGc2lrX8wos7EeNHU62a55pZRr38RXSYzE5D0RcGT8VRcufd/2S7redXbPD79O5mDbZJw8aBqx5DVRH4emakVacg3N+CiiyAYstMfGF0tZSrqQFHNsSukZjo1SktxpgcdmjfKx6yA/sWr3LBKcT1p5uOyVEfKrx30ygtyhrPw=
    on:
      branch: master
      tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
