language: python
python:
- '3.5'
- '3.6'

install:
- sudo apt-get update
- pip install -r requirements.txt
- pip install .

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

script:
- python setup.py test

deploy:
  # pypy test deployment
  - provider: pypi
    distributions: sdist
    server: https://test.pypi.org/legacy/
    user: cklb
    password:
      secure: "RFhhji6sTYurQ7cgvuP11Wx40RgHkUiM02ajESFfQ5nKh1f5698wBVm+ZyB2LGk64MSKhlXQIO1Kqph9XXpXqzMop+O+FOALKBwG+aWsmky3junb/Y0UUkdc+FeJaZcHt3Q5acqo3e8ZHgYuV+6b41RV7WmpFULwaTP61vCNu0BzfykQ5l8DKD9MYYUUZWIUf8PYbWPoshjq+YNOaiVsYpUucbKIK+62OFuLcv/0kSD4fDFoo8c4PdakVbsVLn+ZA5eNO1bfdmbeedRdDa3JYWcsA02jvPAMZlN+xwTNY82zkwYvp/DNOz21XFcfucw3hlWfiNH5NSqvQcOT3KL5yyFM297CtL1Fsb6tc84SSy0mxZLJMEWcA8NKiUkIDzbRJQUOeaghWXFl5/TXP8NNy1GIUuBHhddewJA0qY9EmvAvKI/gLRNpoaeBc9TWUrtdoMtiLiQ8Gay3nS8NzJpjlvQjp5ICPHwDSoJkELrZI2T5xnilnUWZ1vY9oo2ETMQKLo+qUjCyYxue9P08KVwxApfKP37l6ZefBNRpn5KjW1TrnwG2szVzMvHWDl1MqULssmRfltj5elR0VcRvvJTUVBWpBfEd6mjO6ZmDOovy4Qj0SnPuam1MaKc/vvZZUEWLYftMizO3IxedKGyzyPL71FEG6NhSPcYwSEWtBVwXDVk="
    on:
      branch: master
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "3.6"

  # pypy deployment
  - provider: pypi
    distributions: sdist
    user: cklb
    password:
      secure: "WKFKDgsXpoNPPedpgG6W7avL7CHbsFYtTbd41QlnJiBd2qBsI0x2qYsGVrQgC8adCwh8prXCLp+Xs+xR259tyGo6uzrJg/6WyNx5D9IWORizUI7Wa3odYwoK0jN/vK4Rq9TttKbCYI7hjQFs0Dbj+wIZMuPdutqVBSTfPEbOZYKBN2wrqO0gtH5Wc4wjEvWSrGacxmJ1gQaZqwu0LsgbQPjH7wFFV6qX//gOQUEaRNWU6UjoJnLVFV3bhc2GmdGRx7y2qUkP7SQmJoGCB2rtWOT+DeMjbZqq1IplUoWZPJs8cSei8nm+L1wA4DhFUVbm1IhhSHREpMA+KwLbygp79ml2QCOvrHmU+T5SmyHkvI8FJAMX28KuinUU2RC4VIJuvKhTS+IS7yBKOoV1lismMgGbtWafhEHUz6YKOoIDjSPaNOA1/9E2xsIxBXeFmoEDx6tO4wCGT3/da79e8b5Iv6gDR0LdqMD4Dmfzdy7CAbHFw21QwwncSc6t6scYUPUHMfFGc2lrX8wos7EeNHU62a55pZRr38RXSYzE5D0RcGT8VRcufd/2S7redXbPD79O5mDbZJw8aBqx5DVRH4emakVacg3N+CiiyAYstMfGF0tZSrqQFHNsSukZjo1SktxpgcdmjfKx6yA/sWr3LBKcT1p5uOyVEfKrx30ygtyhrPw="
    on:
      branch: master
      tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
