language: python
python:
- '3.5'
- '3.6'

install:
- sudo apt-get update
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file requirements.txt
- conda install pyqt
- source activate test-environment
- python setup.py install

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3

script:
- python setup.py test

deploy:
  provider: pypi
  distributions: sdist
  server: https://testpypi.python.org/pypi
  user: cklb
  password:
    secure: WKFKDgsXpoNPPedpgG6W7avL7CHbsFYtTbd41QlnJiBd2qBsI0x2qYsGVrQgC8adCwh8prXCLp+Xs+xR259tyGo6uzrJg/6WyNx5D9IWORizUI7Wa3odYwoK0jN/vK4Rq9TttKbCYI7hjQFs0Dbj+wIZMuPdutqVBSTfPEbOZYKBN2wrqO0gtH5Wc4wjEvWSrGacxmJ1gQaZqwu0LsgbQPjH7wFFV6qX//gOQUEaRNWU6UjoJnLVFV3bhc2GmdGRx7y2qUkP7SQmJoGCB2rtWOT+DeMjbZqq1IplUoWZPJs8cSei8nm+L1wA4DhFUVbm1IhhSHREpMA+KwLbygp79ml2QCOvrHmU+T5SmyHkvI8FJAMX28KuinUU2RC4VIJuvKhTS+IS7yBKOoV1lismMgGbtWafhEHUz6YKOoIDjSPaNOA1/9E2xsIxBXeFmoEDx6tO4wCGT3/da79e8b5Iv6gDR0LdqMD4Dmfzdy7CAbHFw21QwwncSc6t6scYUPUHMfFGc2lrX8wos7EeNHU62a55pZRr38RXSYzE5D0RcGT8VRcufd/2S7redXbPD79O5mDbZJw8aBqx5DVRH4emakVacg3N+CiiyAYstMfGF0tZSrqQFHNsSukZjo1SktxpgcdmjfKx6yA/sWr3LBKcT1p5uOyVEfKrx30ygtyhrPw=
  on:
    branch: master
    tags: false
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
